title = "RCOS"
baseURL = "https://rcos.io"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Blog"
    title = "blog section"
    url = "/post/"
    weight = -110

  [[menu.main]]
    identifier = "talk"
    name = "Talks"
    url = "/talk/"
    weight = 10

  [[menu.main]]
    identifier = "project"
    name = "Projects"
    title = "Projects"
    url = "/project/"
    weight = 20

  [[menu.main]]
    identifier = "user"
    name = "Developers"
    url = "/user/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "/donate/"
    weight = 50


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
